### ISSUE TITLE
Generate button not working

### ISSUE THREAD

**Issue by dinoypp** [arcanis/secretsanta#6] opened 2019-12-02 15:42 UTC
Was working a few weeks ago. Today, it doesn't generate any links! I have tried different browsers and clearing my cache.

**Comment by arcanis** [comment] 2019-12-02 15:44
I've just tried and it seems to work (I tried with "Foo" on one line and "Bar" on another) - can you share the content you paste in the box?

**Comment by bikerusl** [comment] 2019-12-05 08:55
Hi, I was also having the button doing nothing on Firefox. I didn't bother resetting my cache.

I tried
`Santa
Elf
Krampus
Ms. Klaus
Elvis
Rudolf
Santa !Ms. Klaus
Santa =Krampus`

...which didn't work.

I a list with no other rules that did work.

Then I did:
`Santa
Elf
Krampus
Ms. Klaus
Elvis
Rudolf
Rudolf !Elvis`

which didn't work. but then I tried: 
`Santa
Elf
Krampus
Ms. Klaus
Elvis
Rudolf !Elvis`

Which did work.

So I'm assuming the syntax is each name can only be given once at the start of a line? But can be used multiple times in various rules?

Could you maybe make a few example case templates for us to clarify syntax? I always find an example easier than a described explanation. And having a few cases to look at makes it easier to see.

Thanks for making this :-D So many times we've done a commercial one and it spams you for years afterwards. This is much better.

**Comment by jmelett** [comment] 2021-12-14 10:11
I think the issue is related to the "matching" function. When using following parameters, everything works:
```Dog
Cat
Elephant
Mouse
Tiger
```

As soon you add the matching part, the console throws an error
```Dog
Cat
Elephant
Mouse
Tiger

Tiger =Mouse
```
`SecretSanta.js:13 Uncaught Error: Cannot redefine Tiger
    at SecretSanta.add (SecretSanta.js:13)
    at HTMLFormElement.generate ((index):377)
SecretSanta.add @ SecretSanta.js:13
generate @ (index):377`

Unfortunately I don't know any JS to help, but maybe this helps to narrow it down.

**Comment by arcanis** [comment] 2024-11-26 00:37
I rewrote the app, so I'm going to close this issue for now. The root issue has likely been fixed.

**Closed by arcanis** 2024-11-26 00:37 UTC
